# Generated by Django 4.2.1 on 2023-06-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/'),
        ),
    ]
