# Generated by Django 4.2.1 on 2023-06-20 07:04

import cookie.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookie", "0002_alter_cookie_description_alter_cookie_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookie",
            name="image",
            field=models.ImageField(null=True, upload_to=cookie.models.upload_images),
        ),
    ]
